---
name: WWW-Blogger
version: 2006.0520
author:
  - 'Eric R. Meyers <ermeyers@adelphia.net>'
abstract: Interface to bundle modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTTP::Cookies: 0
  LWP::UserAgent: 0
  perl: 5.6.1
build_requires:
  Test::More: 0
recommends:
  Test::Memory::Cycle: 0
  Test::Pod: 0
  Test::Taint: 0
  Test::Warn: 0
provides:
  WWW::Blogger:
    file: lib/WWW/Blogger.pm
  WWW::Blogger::Com:
    file: lib/WWW/Blogger/Com.pm
  WWW::Blogger::HTML:
    file: lib/WWW/Blogger/HTML.pm
  WWW::Blogger::HTML::API:
    file: lib/WWW/Blogger/HTML/API.pm
  WWW::Blogger::ML:
    file: lib/WWW/Blogger/ML.pm
  WWW::Blogger::ML::API:
    file: lib/WWW/Blogger/ML/API.pm
  WWW::Blogger::XML:
    file: lib/WWW/Blogger/XML.pm
  WWW::Blogger::XML::API:
    file: lib/WWW/Blogger/XML/API.pm
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
