---
name: WWW-Blogger
version: 2008.1017
author:
  - 'Eric R. Meyers <Eric.R.Meyers@gmail.com>'
abstract: Interface to www.blogger.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  AppConfig::Std: 0
  Data::Dumper: 0
  Date::Format: 0
  File::Basename: 0
  FindBin: 0
  LWP::UserAgent: '>= 2.032'
  Net::Google::GData: 0
  XML::Atom::Syndication: 0
  XML::Dumper: 0
  XML::TreeBuilder: 0
  perl: '>= 5.8.0'
build_requires:
  Test::More: 0
recommends:
  Test::Memory::Cycle: 0
  Test::Pod: 0
  Test::Taint: 0
  Test::Warn: 0
provides:
  WWW::Blogger:
    file: lib/WWW/Blogger.pm
    version: 2008.1017
  WWW::Blogger::ML:
    file: lib/WWW/Blogger/ML.pm
    version: 2008.1017
  WWW::Blogger::ML::API:
    file: lib/WWW/Blogger/ML/API.pm
    version: 2008.1017
  WWW::Blogger::XML:
    file: lib/WWW/Blogger/XML.pm
    version: 2008.1017
  WWW::Blogger::XML::API:
    file: lib/WWW/Blogger/XML/API.pm
    version: 2008.1017
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
